// Madani IT Server — নির্দিষ্ট Gmail + Password ছাড়া প্রবেশ অসম্ভব
require('dotenv').config();
const express = require('express');
const http = require('http');
const path = require('path');
const fs = require('fs');
const helmet = require('helmet');
const cors = require('cors');
const rateLimit = require('express-rate-limit');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const { Server } = require('socket.io');
const multer = require('multer');

const PORT = process.env.PORT || 3000;
const JWT_SECRET = process.env.JWT_SECRET || 'change-me';
const GMAIL_USER = process.env.GMAIL_USER || '';
const GMAIL_PASS = process.env.GMAIL_PASS || '';
const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_KEY = process.env.SUPABASE_KEY || '';
let ALLOWED_EMAILS = (process.env.ALLOWED_EMAILS || '')
  .split(',').map(s => s.trim().toLowerCase()).filter(Boolean);
const ADMIN_EMAIL = 'waqfulmadinah@gmail.com';
const MAX_USERS = 30;

// ---- Email transporter (Gmail SMTP) ----
let transporter = null;
if (GMAIL_USER && GMAIL_PASS) {
  const nodemailer = require('nodemailer');
  transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: { user: GMAIL_USER, pass: GMAIL_PASS }
  });
  console.log('✅ Email transporter ready:', GMAIL_USER);
} else {
  console.log('⚠️ GMAIL_USER/GMAIL_PASS not set — OTP will only appear in server console');
}
async function sendOTPEmail(to, otp) {
  if (!transporter) return false;
  try {
    await transporter.sendMail({
      from: `"Madani IT" <${GMAIL_USER}>`,
      to,
      subject: '🔐 Madani IT — আপনার OTP কোড',
      html: `<div style="font-family:sans-serif;max-width:400px;margin:auto;padding:20px;background:#111b21;color:#e9edef;border-radius:12px">
        <h2 style="color:#00a884;text-align:center">🔐 Madani IT OTP</h2>
        <p>আপনার ৬ ডিজিট verification code:</p>
        <div style="text-align:center;font-size:32px;font-weight:bold;letter-spacing:8px;color:#00e676;padding:16px;background:#202c33;border-radius:8px">${otp}</div>
        <p style="color:#8696a0;font-size:12px">এই কোড ৫ মিনিটের জন্য বৈধ। যদি আপনি লগইন করেন না, এই মেইল উপেক্ষা করুন।</p>
      </div>`
    });
    console.log(`📧 OTP sent to ${to}`);
    return true;
  } catch (e) {
    console.error('❌ Email send failed:', e.message);
    return false;
  }
}

const USERS_FILE = path.join(__dirname, 'users.json');
const ENV_FILE = path.join(__dirname, '.env');

function persistAllowedEmails() {
  try {
    let env = fs.existsSync(ENV_FILE) ? fs.readFileSync(ENV_FILE, 'utf8') : '';
    const line = `ALLOWED_EMAILS=${ALLOWED_EMAILS.join(',')}`;
    if (/^ALLOWED_EMAILS=.*$/m.test(env)) env = env.replace(/^ALLOWED_EMAILS=.*$/m, line);
    else env += (env.endsWith('\n') ? '' : '\n') + line + '\n';
    fs.writeFileSync(ENV_FILE, env, 'utf8');
  } catch (e) { console.error('persist .env error', e.message); }
}

// ---- User store (users.json) ----
function loadUsers() {
  try {
    if (fs.existsSync(USERS_FILE)) return JSON.parse(fs.readFileSync(USERS_FILE, 'utf8'));
  } catch (e) { console.error('users.json read error', e.message); }
  return {};
}
function saveUsers(u) { fs.writeFileSync(USERS_FILE, JSON.stringify(u, null, 2), 'utf8'); }

let users = loadUsers();
(function seed() {
  let changed = false;
  const defs = (process.env.DEFAULT_PASSWORDS || '').split(',').map(s => s.trim()).filter(Boolean);
  for (const d of defs) {
    const i = d.indexOf(':');
    if (i < 0) continue;
    const email = d.slice(0, i).trim().toLowerCase();
    const pass = d.slice(i + 1);
    if (!ALLOWED_EMAILS.includes(email)) continue;
    if (!users[email]) {
      users[email] = { hash: bcrypt.hashSync(pass, 10), name: email.split('@')[0], displayName: email.split('@')[0], registered: true, createdAt: Date.now() };
      changed = true;
    }
  }
  const defaultPassMap = { 'waqfulmadinah@gmail.com': 'Waqf1234' };
  for (const email of ALLOWED_EMAILS) {
    if (!users[email]) {
      const autoPass = defaultPassMap[email] || ('Pass' + email.split('@')[0].replace(/[^a-zA-Z0-9]/g, '') + '123');
      const regCode = Math.random().toString(36).slice(2, 8).toUpperCase();
      users[email] = { hash: bcrypt.hashSync(autoPass, 10), name: email.split('@')[0], displayName: email.split('@')[0], registered: true, regCode, createdAt: Date.now(), autoGenerated: true };
      changed = true;
      console.log(`Auto-created: ${email} | pass: ${autoPass} | reg-code: ${regCode}`);
    }
    if (!users[email].displayName) { users[email].displayName = users[email].name || email.split('@')[0]; changed = true; }
    if (!users[email].regCode) { users[email].regCode = Math.random().toString(36).slice(2, 8).toUpperCase(); changed = true; }
    if (users[email].registered === undefined) { users[email].registered = true; changed = true; }
  }
  if (changed) saveUsers(users);
  console.log('Allowed emails:', ALLOWED_EMAILS.join(', ') || '(খালি!)');
})();

const app = express();
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors());
app.use(express.json({ limit: '15mb' }));

// ---- File uploads (multer temp) ----
const uploadsDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir, { recursive: true });
const storage = multer.memoryStorage();
const upload = multer({ storage, limits: { fileSize: 50 * 1024 * 1024 } });

// ---- Supabase Storage helper ----
async function uploadToSupabase(buffer, fileName, mimeType) {
  if (!SUPABASE_URL || !SUPABASE_KEY) return null;
  const ext = path.extname(fileName) || '.' + (mimeType.split('/')[1] || 'bin');
  const folder = mimeType.split('/')[0] || 'file';
  const storePath = `${folder}/${Date.now()}-${Math.random().toString(36).slice(2,8)}${ext}`;
  const r = await fetch(`${SUPABASE_URL}/storage/v1/object/Media/${storePath}`, {
    method: 'POST',
    headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}`, 'Content-Type': mimeType, 'x-upsert': 'true' },
    body: buffer
  });
  if (!r.ok) { console.error('Supabase upload error:', r.status, await r.text()); return null; }
  return `${SUPABASE_URL}/storage/v1/object/public/Media/${storePath}`;
}

app.use(express.static(path.join(__dirname, 'public'), {
  setHeaders: (res, p) => {
    if (p.endsWith('.js') || p.endsWith('.css')) {
      res.set('Cache-Control', 'no-store, no-cache, must-revalidate');
    }
  }
}));
app.use('/uploads', express.static(uploadsDir));

const loginLimiter = rateLimit({ windowMs: 10 * 60 * 1000, max: 30, message: { error: 'অনেকবার চেষ্টা করেছেন। ১০ মিনিট পর আবার চেষ্টা করুন।' } });

// ---- Auth helpers ----
function signToken(email) {
  return jwt.sign({ email }, JWT_SECRET, { expiresIn: '7d' });
}
function adminMiddleware(req, res, next) {
  if (req.email !== ADMIN_EMAIL) return res.status(403).json({ error: 'শুধু অ্যাডমিন এই কাজ করতে পারবে।' });
  next();
}
function authMiddleware(req, res, next) {
  const h = req.headers.authorization || '';
  const token = h.startsWith('Bearer ') ? h.slice(7) : null;
  if (!token) return res.status(401).json({ error: 'লগইন প্রয়োজন' });
  try {
    const p = jwt.verify(token, JWT_SECRET);
    if (!ALLOWED_EMAILS.includes(p.email.toLowerCase())) return res.status(403).json({ error: 'অনুমতি নেই' });
    req.email = p.email.toLowerCase();
    next();
  } catch {
    return res.status(401).json({ error: 'সেশন শেষ। আবার লগইন করুন।' });
  }
}

// ---- 2FA OTP Store ----
const otpStore = new Map();
function generateOTP() { return String(Math.floor(100000 + Math.random() * 900000)); }

function buildUserList() {
  return ALLOWED_EMAILS.map(e => ({
    email: e,
    name: (users[e] || {}).displayName || (users[e] || {}).name || e.split('@')[0],
    avatar: (users[e] || {}).avatar || null,
    online: onlineMap.has(e)
  }));
}

// ---- Routes ----
// 1) Login
app.post('/api/login', loginLimiter, async (req, res) => {
  const email = String(req.body.email || '').trim().toLowerCase();
  const password = String(req.body.password || '');

  if (!email.endsWith('@gmail.com')) return res.status(403).json({ error: 'শুধুমাত্র Gmail দিয়ে প্রবেশ করা যাবে।' });
  if (!ALLOWED_EMAILS.includes(email)) {
    console.log('Blocked login attempt:', email);
    return res.status(403).json({ error: 'এই Gmail-এর প্রবেশাধিকার নেই। রেজিস্ট্রেশন করুন।' });
  }
  const u = users[email];
  if (!u) return res.status(403).json({ error: 'এই অ্যাকাউন্ট এখনো সক্রিয় করা হয়নি।' });
  if (!bcrypt.compareSync(password, u.hash)) return res.status(401).json({ error: 'ভুল পাসওয়ার্ড।' });

  if (u.twoFactorEnabled) {
    const otp = generateOTP();
    otpStore.set(email, { otp, expiresAt: Date.now() + 5 * 60 * 1000 });
    console.log(`[2FA] OTP for ${email}: ${otp}`);
    const emailSent = await sendOTPEmail(email, otp);
    const hint = emailSent
      ? `OTP আপনার Gmail-এ পাঠানো হয়েছে: ${email}`
      : `OTP সার্ভার কনসোলে: ${otp}`;
    return res.json({ require2FA: true, email, hint, emailSent });
  }

  const token = signToken(email);
  res.json({ token, email, name: u.displayName || u.name, displayName: u.displayName || u.name, avatar: u.avatar || null, allowedUsers: buildUserList() });
});

// 1b) 2FA verify
app.post('/api/verify-otp', loginLimiter, (req, res) => {
  const email = String(req.body.email || '').trim().toLowerCase();
  const otp = String(req.body.otp || '');
  const stored = otpStore.get(email);
  if (!stored || stored.expiresAt < Date.now()) return res.status(400).json({ error: 'OTP মেয়াদ শেষ। আবার লগইন করুন।' });
  if (stored.otp !== otp) return res.status(401).json({ error: 'ভুল OTP।' });
  otpStore.delete(email);
  const u = users[email] || {};
  const token = signToken(email);
  res.json({ token, email, name: u.displayName || u.name, displayName: u.displayName || u.name, avatar: u.avatar || null, allowedUsers: buildUserList() });
});

// 1d) Self-registration
app.post('/api/register', loginLimiter, (req, res) => {
  const email = String(req.body.email || '').trim().toLowerCase();
  const password = String(req.body.password || '');
  const name = String(req.body.name || '').trim() || email.split('@')[0];

  if (!email.endsWith('@gmail.com')) return res.status(400).json({ error: 'শুধুমাত্র Gmail (@gmail.com) দিয়ে রেজিস্ট্রেশন করা যাবে।' });
  if (email.length < 10) return res.status(400).json({ error: 'সঠিক Gmail দিন।' });
  if (!password || password.length < 6) return res.status(400).json({ error: 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষর হতে হবে।' });
  if (ALLOWED_EMAILS.length >= MAX_USERS) return res.status(400).json({ error: `সর্বোচ্চ ${MAX_USERS} জন ব্যবহারকারী।` });
  if (ALLOWED_EMAILS.includes(email)) return res.status(400).json({ error: 'এই Gmail আগেই নিবন্ধিত। লগইন করুন।' });

  const regCode = Math.random().toString(36).slice(2, 8).toUpperCase();
  ALLOWED_EMAILS.push(email);
  users[email] = {
    hash: bcrypt.hashSync(password, 10),
    name: email.split('@')[0],
    displayName: name,
    registered: true,
    regCode,
    createdAt: Date.now()
  };
  saveUsers(users);
  persistAllowedEmails();
  console.log(`✅ Self-registered: ${email} | reg-code: ${regCode}`);

  const token = signToken(email);
  res.json({ token, email, name, displayName: name, avatar: null, regCode, allowedUsers: buildUserList() });
});

// 2) Profile
app.get('/api/me', authMiddleware, (req, res) => {
  const u = users[req.email] || {};
  res.json({ email: req.email, name: u.displayName || u.name || req.email.split('@')[0], displayName: u.displayName || u.name, avatar: u.avatar || null, registered: u.registered, regCode: u.regCode, allowedUsers: buildUserList() });
});

app.post('/api/profile/update', authMiddleware, (req, res) => {
  const u = users[req.email]; if (!u) return res.status(404).json({ error: 'Not found' });
  if (req.body.displayName) u.displayName = String(req.body.displayName).trim().slice(0, 30);
  if (req.body.avatar !== undefined) u.avatar = req.body.avatar || null;
  if (req.body.newPassword) {
    if (!req.body.oldPassword) return res.status(400).json({ error: 'পুরনো পাসওয়ার্ড দিন।' });
    if (!bcrypt.compareSync(String(req.body.oldPassword), u.hash)) return res.status(401).json({ error: 'পুরনো পাসওয়ার্ড ভুল।' });
    if (req.body.newPassword.length < 6) return res.status(400).json({ error: 'নতুন পাসওয়ার্ড ৬+ অক্ষর হতে হবে।' });
    u.hash = bcrypt.hashSync(req.body.newPassword, 10);
  }
  saveUsers(users);
  res.json({ ok: true, displayName: u.displayName, avatar: u.avatar || null });
});

app.get('/api/profiles', authMiddleware, (req, res) => {
  const profiles = {};
  for (const email of ALLOWED_EMAILS) {
    const u = users[email] || {};
    profiles[email] = { email, name: u.displayName || u.name || email.split('@')[0], avatar: u.avatar || null };
  }
  res.json(profiles);
});

app.get('/api/profile/:email', authMiddleware, (req, res) => {
  const email = req.params.email.toLowerCase();
  const u = users[email];
  if (!u) return res.status(404).json({ error: 'Not found' });
  res.json({ email, name: u.displayName || u.name, displayName: u.displayName || u.name, avatar: u.avatar || null });
});

// 2FA
app.post('/api/2fa/enable', authMiddleware, async (req, res) => {
  const u = users[req.email]; if (!u) return res.status(404).json({ error: 'Not found' });
  u.twoFactorEnabled = true; saveUsers(users);
  const otp = generateOTP(); otpStore.set(req.email, { otp, expiresAt: Date.now() + 5 * 60 * 1000 });
  console.log(`[2FA] Test OTP for ${req.email}: ${otp}`);
  const emailSent = await sendOTPEmail(req.email, otp);
  const msg = emailSent ? '2FA সক্রিয়। OTP Gmail-এ পাঠানো হয়েছে।' : '2FA সক্রিয়। OTP: ' + otp;
  res.json({ ok: true, message: msg });
});
app.post('/api/2fa/disable', authMiddleware, (req, res) => {
  const u = users[req.email]; if (!u) return res.status(404).json({ error: 'Not found' });
  u.twoFactorEnabled = false; saveUsers(users);
  res.json({ ok: true, message: '2FA নিষ্ক্রিয়।' });
});

// Password change
app.post('/api/change-password', authMiddleware, (req, res) => {
  const { oldPassword, newPassword } = req.body;
  if (!newPassword || newPassword.length < 6) return res.status(400).json({ error: 'নতুন পাসওয়ার্ড ৬+ অক্ষর হতে হবে।' });
  const u = users[req.email];
  if (!bcrypt.compareSync(String(oldPassword || ''), u.hash)) return res.status(401).json({ error: 'পুরনো পাসওয়ার্ড ভুল।' });
  u.hash = bcrypt.hashSync(String(newPassword), 10);
  saveUsers(users);
  res.json({ ok: true, message: 'পাসওয়ার্ড বদলে গেছে।' });
});

// File upload
app.post('/api/upload', authMiddleware, upload.single('file'), async (req, res) => {
  if (!req.file) return res.status(400).json({ error: 'ফাইল পাওয়া যায়নি।' });
  try {
    const supabaseUrl = await uploadToSupabase(req.file.buffer, req.file.originalname, req.file.mimetype);
    if (supabaseUrl) {
      return res.json({ url: supabaseUrl, fileName: req.file.originalname, mimeType: req.file.mimetype, size: req.file.size });
    }
  } catch (e) { console.error('Supabase upload failed, falling back to local:', e.message); }
  // Fallback: local storage
  const ext = path.extname(req.file.originalname) || '.' + (req.file.mimetype.split('/')[1] || 'bin');
  const fname = Date.now() + '-' + Math.random().toString(36).slice(2, 8) + ext;
  fs.writeFileSync(path.join(uploadsDir, fname), req.file.buffer);
  res.json({ url: '/uploads/' + fname, fileName: req.file.originalname, mimeType: req.file.mimetype, size: req.file.size });
});

// Admin
app.get('/api/admin/users', authMiddleware, adminMiddleware, (req, res) => {
  res.json({
    max: MAX_USERS, count: ALLOWED_EMAILS.length, admin: ADMIN_EMAIL,
    users: ALLOWED_EMAILS.map(e => ({
      email: e, name: (users[e] || {}).displayName || (users[e] || {}).name || e.split('@')[0],
      avatar: (users[e] || {}).avatar || null, regCode: (users[e] || {}).regCode || null,
      online: onlineMap.has(e), createdAt: (users[e] || {}).createdAt || null
    }))
  });
});
app.post('/api/admin/add-user', authMiddleware, adminMiddleware, (req, res) => {
  const email = String(req.body.email || '').trim().toLowerCase();
  const password = String(req.body.password || '');
  const name = String(req.body.name || '').trim() || email.split('@')[0];
  if (!email.endsWith('@gmail.com')) return res.status(400).json({ error: 'শুধু Gmail যোগ করা যাবে।' });
  if (email.length < 10) return res.status(400).json({ error: 'সঠিক Gmail দিন।' });
  if (ALLOWED_EMAILS.includes(email)) return res.status(400).json({ error: 'এই Gmail আগেই আছে।' });
  if (ALLOWED_EMAILS.length >= MAX_USERS) return res.status(400).json({ error: `সর্বোচ্চ ${MAX_USERS} জন।` });
  if (!password || password.length < 6) return res.status(400).json({ error: 'পাসওয়ার্ড ৬+ অক্ষর হতে হবে।' });
  ALLOWED_EMAILS.push(email);
  const regCode = Math.random().toString(36).slice(2, 8).toUpperCase();
  users[email] = { hash: bcrypt.hashSync(password, 10), name: email.split('@')[0], displayName: name, registered: false, regCode, createdAt: Date.now() };
  saveUsers(users); persistAllowedEmails();
  res.json({ ok: true, message: 'যোগ করা হয়েছে', email, regCode });
});
app.post('/api/admin/remove-user', authMiddleware, adminMiddleware, (req, res) => {
  const email = String(req.body.email || '').trim().toLowerCase();
  if (email === ADMIN_EMAIL) return res.status(400).json({ error: 'অ্যাডমিন নিজেকে সরাতে পারবে না।' });
  if (!ALLOWED_EMAILS.includes(email)) return res.status(404).json({ error: 'তালিকায় নেই।' });
  ALLOWED_EMAILS = ALLOWED_EMAILS.filter(e => e !== email);
  delete users[email];
  saveUsers(users); persistAllowedEmails();
  const sid = onlineMap.get(email);
  if (sid) { try { io.to(sid).emit('force-logout', { reason: 'আপনাকে তালিকা থেকে সরানো হয়েছে।' }); io.sockets.sockets.get(sid)?.disconnect(true); } catch {} }
  res.json({ ok: true, message: 'সরানো হয়েছে', email });
});
app.post('/api/admin/reset-password', authMiddleware, adminMiddleware, (req, res) => {
  const email = String(req.body.email || '').trim().toLowerCase();
  const password = String(req.body.password || '');
  if (!ALLOWED_EMAILS.includes(email)) return res.status(404).json({ error: 'তালিকায় নেই।' });
  if (!password || password.length < 6) return res.status(400).json({ error: 'পাসওয়ার্ড ৬+ অক্ষর হতে হবে।' });
  users[email] = { ...(users[email] || {}), hash: bcrypt.hashSync(password, 10), name: users[email]?.name || email.split('@')[0] };
  saveUsers(users);
  res.json({ ok: true, message: 'পাসওয়ার্ড রিসেট হয়েছে' });
});

// Messages
const messages = [];
app.get('/api/messages', authMiddleware, (req, res) => {
  const now = Date.now();
  const visible = messages.filter(m => !m.expiresAt || m.expiresAt > now)
    .filter(m => m.to === 'group' || m.from === req.email || m.to === req.email)
    .slice(-200);
  res.json(visible);
});

// ---- Socket.io ----
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: '*' }, maxHttpBufferSize: 50e6 });
const onlineMap = new Map();

// Group call rooms: roomId -> Set of emails
const callRooms = new Map();

io.use((socket, next) => {
  try {
    const token = socket.handshake.auth.token;
    const p = jwt.verify(token, JWT_SECRET);
    const email = p.email.toLowerCase();
    if (!ALLOWED_EMAILS.includes(email)) return next(new Error('forbidden'));
    socket.email = email;
    next();
  } catch { next(new Error('unauthorized')); }
});

io.on('connection', (socket) => {
  const email = socket.email;
  onlineMap.set(email, socket.id);
  io.emit('presence', { email, online: true, onlineList: [...onlineMap.keys()] });

  // Chat messages
  socket.on('chat:message', (data = {}) => {
    const text = String(data.text || '').slice(0, 2000);
    if (!text.trim() && !data.voice && !data.media) return;
    const msg = {
      id: 'm' + Date.now() + Math.floor(Math.random() * 9999),
      from: email,
      to: data.to || 'group',
      text, type: data.media ? (data.media.mimeType || 'image').split('/')[0] : data.voice ? 'voice' : 'text',
      voice: data.voice || null,
      media: data.media || null,
      replyTo: data.replyTo || null,
      at: Date.now(),
      expiresAt: data.disappearSec ? Date.now() + data.disappearSec * 1000 : null
    };
    messages.push(msg);
    if (messages.length > 1000) messages.splice(0, messages.length - 1000);
    if (msg.to === 'group') io.emit('chat:message', msg);
    else {
      socket.emit('chat:message', msg);
      const target = onlineMap.get(msg.to);
      if (target) io.to(target).emit('chat:message', msg);
    }
    socket.emit('chat:ack', { id: msg.id, status: 'sent' });
  });

  socket.on('chat:typing', (d = {}) => socket.broadcast.emit('chat:typing', { from: email, to: d.to || 'group', isTyping: !!d.isTyping }));
  socket.on('chat:read', (d = {}) => socket.broadcast.emit('chat:read', { by: email, id: d.id }));

  // ---- 1-1 Call signaling ----
  socket.on('call:invite', (d = {}) => {
    const target = onlineMap.get(d.to);
    if (target) io.to(target).emit('call:invite', { from: email, kind: d.kind || 'video' });
  });
  socket.on('call:signal', (d = {}) => {
    const target = onlineMap.get(d.to);
    if (target) io.to(target).emit('call:signal', { from: email, signal: d.signal });
  });
  socket.on('call:end', (d = {}) => {
    const target = onlineMap.get(d.to);
    if (target) io.to(target).emit('call:end', { from: email });
  });

  // ---- Group call signaling ----
  socket.on('groupcall:join', (d = {}) => {
    const roomId = d.roomId || 'group';
    socket.join('call:' + roomId);
    if (!callRooms.has(roomId)) callRooms.set(roomId, new Set());
    const room = callRooms.get(roomId);
    const participants = [...room];
    room.add(email);
    console.log(`📞 Group call: ${email} joined room ${roomId} (${room.size} participants)`);
    // Tell existing participants about the new user
    for (const p of participants) {
      const sid = onlineMap.get(p);
      if (sid) io.to(sid).emit('groupcall:new-peer', { from: email, roomId });
    }
    // Tell the new user about existing participants
    socket.emit('groupcall:peers', { peers: participants, roomId });
  });

  socket.on('groupcall:signal', (d = {}) => {
    const target = onlineMap.get(d.to);
    if (target) io.to(target).emit('groupcall:signal', { from: email, signal: d.signal, roomId: d.roomId });
  });

  socket.on('groupcall:leave', (d = {}) => {
    const roomId = d.roomId || 'group';
    socket.leave('call:' + roomId);
    const room = callRooms.get(roomId);
    if (room) {
      room.delete(email);
      if (room.size === 0) { callRooms.delete(roomId); console.log(`📞 Room ${roomId} empty — deleted`); }
      else {
        for (const p of room) {
          const sid = onlineMap.get(p);
          if (sid) io.to(sid).emit('groupcall:peer-left', { from: email, roomId });
        }
      }
    }
  });

  socket.on('disconnect', () => {
    if (onlineMap.get(email) === socket.id) onlineMap.delete(email);
    io.emit('presence', { email, online: false, onlineList: [...onlineMap.keys()] });
    // Clean up group calls
    for (const [roomId, room] of callRooms) {
      if (room.has(email)) {
        room.delete(email);
        for (const p of room) {
          const sid = onlineMap.get(p);
          if (sid) io.to(sid).emit('groupcall:peer-left', { from: email, roomId });
        }
        if (room.size === 0) callRooms.delete(roomId);
      }
    }
  });
});

server.listen(PORT, () => console.log(`Madani IT চলছে: http://localhost:${PORT}`));
